### ISSUE TITLE
Attachments also saved?

### ISSUE THREAD

**Issue by robdejonge** [storizzi/notes-exporter#1]
Your exporter looks quite comprehensive. 

I'm looking for something like this, but my Notes contain quite a few attachments of all kinds. I was actually searching on how to save them using AppleScript, when I happened upon this repo. 

I've seen how I can get it to save image files, and reading the source it really does seem to just be about image files. 

Wondering ... does it also support saving other types of attachments?

**Comment by storizzi** [comment]
Hi - can you give me an idea of the kind of files you are including in the notes, then I can do a test to see if that could be accommodated. I'll be honest, I have never tried embedding anything other than images in notes.

**Comment by robdejonge** [comment]
Me personally ... I store all sorts of documents in Notes. The majority is PDF files, but also Numbers, Pages, Word and Excel documents for example.

**Comment by storizzi** [comment]
Hi - I haven't been able to find an obvious way of doing this - these are not embedded in the html in the same way that images are unfortunately

**Comment by rokesby** [comment]
Thank you @storizzi . I use the quick capture function of Apple Notes to scan in documents of all kinds, so I have a lot of PDF files embedded in the notes. It would be lovely to have this feature :-)

**Comment by storizzi** [comment]
Yes - unfortunately Apple's support for scripting is very spotty (it is even worse for To Dos). I'll close this one as I don't have a good solution. Thanks for the request though.
