### ISSUE TITLE
option to use the note ID as the filename, or as a portion of the filename.

### ISSUE THREAD

**Issue by cromulus** [storizzi/notes-exporter#3]
I am attempting to export all of my notes on a regular basis and store them in a vector database for Retrieval Augmented Generation with an LLM.

In order to do this effectively, I need to be able to track notes regardless of the title of the note, which can change. From what I understand, each note has an underlying, static ID. I would love to be able to save the filename with that ID such that when I export, I am able to update the vector database with the new content regardless of changes to the title of the note.

Here is some AppleScript to get the id of a note:
https://stackoverflow.com/questions/68362500/get-id-of-selected-apple-note-in-applescript

Thank you for putting all the work into this! It's amazing!

Update:
I noticed that it's on your Todo list! Hah! great minds and all that.

**Comment by storizzi** [comment]
This is now available with some stuff with conda environment creation / removal in a new release - thanks for the suggestion
